version: "2"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    tty: true
    networks:
      - none
  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    tty: true
networks:
  none:
    external:
      name: none
