# Overrides of Compose services used to help develop faster without rebuilding
# the container on every change.
version: "2"
services:
  test:
    volumes:
      - ./lint_and_test.sh:/test/lint_and_test.sh:ro
      - ./slack_retro_bot_to_airtable.py:/test/slack_retro_bot_to_airtable.py:ro
      - ./slack_retro_bot_to_airtable_test.py:/test/slack_retro_bot_to_airtable_test.py:ro
      - ./slack_retro_bot_notification_example.txt:/test/slack_retro_bot_notification_example.txt:ro
      - ./.pylintrc:/test/.pylintrc:ro
      - ./.pycodestyle:/test/.pycodestyle:ro
    environment:
      AIRTABLE_RETRO_BASE_ID:
      AIRTABLE_MOOD_BASE_ID:
      AIRTABLE_RETRO_API_KEY:
      SLACK_RETRO_TOKEN:
  deploy:
    volumes:
      - ./entrypoint.deploy.sh:/var/task/entrypoint.sh:ro
      - ./slack_retro_bot_to_airtable.py:/var/task/slack_retro_bot_to_airtable.py:ro
      - ./zappa_settings.json:/var/task/zappa_settings.json:ro
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    environment:
      AWS_DEFAULT_REGION:
