version: "2"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    tty: true
    networks:
      - none
  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    tty: true
    environment:
      AWS_SECRET_ACCESS_KEY:
      AWS_ACCESS_KEY_ID:
networks:
  none:
    external:
      name: none
