# Zappa (and AWS Lambda) support the following versions of Python: ['2.7', '3.6']
# https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html
FROM python:3.6

WORKDIR /test

COPY requirements.txt requirements-test.txt ./
RUN pip install -r ./requirements-test.txt

COPY * ./

CMD './lint_and_test.sh'
