# Zappa (and AWS Lambda) support the following versions of Python: ['2.7', '3.6']
# https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html
FROM python:3.6

WORKDIR /var/task
COPY ./requirements.txt ./requirements.txt
COPY ./entrypoint.deploy.sh ./entrypoint.sh

RUN pip install --upgrade pip setuptools pipenv
RUN pipenv --three install -r ./requirements.txt

ENTRYPOINT ["./entrypoint.sh"]
